#! /usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Scalar::Util qw( looks_like_number );

sub interpret {
  my %translation =
    (
      '+' => '$ram[$p]++;',
      '-' => '$ram[$p]--;',
      '>' => '$p++;',
      '<' => '$p--;',
      '[' => '{my$r=$ram[$p];while($ram[$p]=ref$r?shift@$r:looks_like_number$r?$ram[$p]:ord substr$r//"\0",0,1,""){',
      ']' => '}}',
      '.' => '$output.=defined$ram[$p]&&looks_like_number$ram[$p]?chr$ram[$p]:$ram[$p];',
      ',' => '$ram[$p]=shift@args;',
    );
  my ($template,@args) = @_;
  my $program = '';
  for my $c ( $template =~ /./gs ) {
    my $op = $translation{$c};
    $program .= $op // "\$output .= '$c';";
  }

  my @ram;
  my $p = 0;
  my $output = '';

  eval $program;
  $output;
}

my $template = do { local $/; <DATA> };
print interpret(
  $template,
  'An argument',
  [qw(Iterating on an array)],
  'Iterating on a string',
  'Qrpelcgvat n zvyvgnel-tenqr pvcure',
);

__DATA__

Straight text

+++[
  * repeated three times
-]

++++++++++[>+++++++>++++++++++>+++>+++++++++<<<<-]
>++.>+.+++++++..+++.>++.>---.<<.+++.------.--------.>+.

,>[-]+++[<.>-]

,[. ]

,[.]

,[[>>++++[>++++++++<-]<+<-[>+>+>-[>>>]<[[>+<-]>>+>]<<<<<-]]>>>[-]+>--[-[<->+++[-]]]<[++++++++++++<[>-[>+>>]>[+[<+>-]>+>>]<<<<<-]>>[<+>-]>[-[-<<[-]>>]<<[<<->>-]>>]<<[<<+>>-]]<[-]<.[-]<-]
