#! /usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Acme::Template::TuringComplete;

my $template = do { local $/; <DATA> };
print Acme::Template::TuringComplete->interpret(
  $template,
  'Badger',
  [qw(Iterating on an array)],
  'Iterating on a string',
  'Qrpelcgvat n zvyvgnel-tenqr pvcure',
);

__DATA__

Straight text

+++[
  * repeated three times
-]

++++++++++[>+++++++>++++++++++>+++>+++++++++<<<<-]
>++.>+.+++++++..+++.>++.>---.<<.+++.------.--------.>+.

,>[-]+++[<{.}>-]

,[.]

,[=.]=

,[[>>++++[>++++++++<-]<+<-[>+>+>-[>>>]<[[>+<-]>>+>]<<<<<-]]>>>[-]+>--[-[<->+++[-]]]<[++++++++++++<[>-[>+>>]>[+[<+>-]>+>>]<<<<<-]>>[<+>-]>[-[-<<[-]>>]<<[<<->>-]>>]<<[<<+>>-]]<[-]<.[-]<-]
